- name: System setup
  hosts: localhost
  vars: 
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    #personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update System
    become: true
    pacman:
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
  - include_tasks: tasks/paru.yml
  - include_tasks: tasks/system.yml
  - include_tasks: tasks/ssh.yml
  - include_tasks: tasks/dotfiles.yml
  - include_tasks: tasks/paru_packages.yml
  - include_tasks: tasks/zsh.yml
