- name: install graphical interface
  become: true
  community.general.pacman:
    name: hyprland
  tags: hyprland

- name: install pywal
  become: true
  community.general.pacman:
    name: python-pywal
  tags: hyprland

- name: install dunst
  become: true
  community.general.pacman:
    name: dunst 
  tags: hyprland

- name: install kitty
  become: true
  community.general.pacman:
    name: kitty 
  tags: terminal

- name: install pass
  become: true
  community.general.pacman:
    name: pass 
  tags: terminal
