- name: Installing stow
  become: true
  community.general.pacman:
    name:
      - stow
  tags: dotfiles

- name: Cloning dotfiles
  become: no
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.git:
    repo: 'git@gitlab.com:HertelP/dotfiles.git'
    dest: "{{ lookup('env', 'HOME')}}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags: dotfiles

- name: Stow files
  ansible.builtin.shell: cd {{ lookup('env', 'HOME')}}/dotfiles && stow .
  tags: dotfiles
