- name: Ensure the AUR builder user exists
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    state: present
    shell: /bin/bash
    create_home: yes

- name: "Clone paru repository from AUR"
  become: no
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: "/home/{{ ansible_user_id }}/paru-build"

- name: "Build and install paru package using makepkg"
  become: no
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: "/home/{{ ansible_user_id }}/paru-build"
    creates: /usr/bin/paru

- name: "Clean up the build directory"
  become: no
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/paru-build"
    state: absent

