- name: install system packages
  become: true
  community.general.pacman: 
    name: 
      - xorg-server
      - xorg-xinit
      - xf86-input-synaptics
      - wl-clipboard
      - qt6ct
      - ripgrep
      - gtk3
      - fzf
      - yazi
      - poppler
      - jq
      - ffmpegthumbnailer
      - openssh
  tags: system

- name: install terminal setup
  become: true
  community.general.pacman:
    name:
      - tmux
      - neovim
      - nerd-fonts
      - zoxide
      - pass
      - ttf-font-awesome
      - dash
  tags: system
