- name: install system packages
  become: true
  community.general.pacman: 
    name: 
      - xorg-server
      - xorg-xinit
      - xf86-input-synaptics
      - qt6ct
      - ripgrep
      - gtk3
      - fzf
      - yazi
      - poppler
      - jq
      - unar
      - ffmpegthumbnailer
      - cliphist
      - wl-clipboard
  tags: system

- name: install terminal setup
  become: true
  community.general.pacman:
    name:
      - tmux
      - neovim
      - nerd-fonts
      - zoxide
      - pass
  tags: terminal

- name: tmux config
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ lookup('env', 'HOME')}}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: source tmux
  ansible.builtin.shell: tmux source ~/.config/tmux/tmux.conf

