- name: Install zsh
  become: true
  community.general.pacman: 
    name: zsh
  tags: zsh 

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: chsh -s /bin/zsh
  tags: zsh

- name: Install dash
  become: true
  community.general.pacman: 
    name: dash
  tags: dash 

- name: Change systemshell to dash
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: ln -sf /bin/dash /bin/sh
  tags: zsh
