- name: Install zsh
  become: true
  community.general.pacman: 
    name: zsh
  tags: zsh 

- name: Find the path of the zsh executable
  ansible.builtin.command: which zsh
  register: zsh_path_result
  changed_when: false 
  check_mode: false  
  tags: zsh

- name: Change shell for user to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path_result.stdout }}" 
  when: zsh_path_result.stdout != "" 
  tags: zsh

- name: Find the path of the dash executable
  ansible.builtin.command: which dash
  register: dash_path_result
  changed_when: false
  check_mode: false
  tags: zsh

- name: Point /bin/sh to dash
  become: true
  ansible.builtin.file:
    src: "{{ dash_path_result.stdout }}" 
    dest: /bin/sh                  
    state: link                     
    force: yes                       
  when: dash_path_result.stdout != ""
  tags: zsh
