- name: install zsh
  become: true
  community.general.pacman: 
    name: zsh
  tags: zsh 

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  tags: zsh
