- name: install zsh
  become: true
  community.general.pacman: 
    name: zsh
  tags: zsh 

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Modify .zshrc
  shell: echo 'autoload -U promptinit; promptinit' >> /home/{{ansible_user_id}}/.zshrc && echo 'prompt pure' >> /home/{{ansible_user_id}}/.zshrc
  tags: pure


